version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: node:16
    container_name: node-rest-api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      POSTGRES_HOST: db
      POSTGRES_DB: yourdbname
      POSTGRES_USER: yourdbuser
      POSTGRES_PASSWORD: yourdbpassword
      JWT_SECRET: 'your_secret_key'
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: yourdbuser
      POSTGRES_PASSWORD: yourdbpassword